Adds hyrax-hirmeos to the gemfile
ubiquitypress/hyku_addons pull request #204
Opened 2021-03-30 12:47 UTC by BertZZ

2021-03-30 18:25 UTC, cjcolvar approved these changes

2021-03-30 20:12 UTC, cjcolvar requested changes
Something is definitely wrong and causing tests to fail.
```
ActionView::Template::Error:
  undefined local variable or method `hyrax_hirmeos' for #<#<Class:0x000055b165f43cd0>:0x000055b17159d698>
  Did you mean?  hyrax_doi
Shared Example Group: "create work user context" called from ./spec/features/create_exhibition_item_spec.rb:9
./vendor/bundle/ruby/2.7.0/bundler/gems/hyrax-hirmeos-e9a23bb451c5/app/views/hyrax/base/show.html.erb:54:in `__home_circleci_project_vendor_bundle_ruby_______bundler_gems_hyrax_hirmeos_e_a__bb___c__app_views_hyrax_base_show_html_erb___361670248595080163_606320'
```

2021-04-07 13:59 UTC, BertZZ commented
Seems there is a different number of failing tests each time. IIRC these are the same ones that were intermittently failing before. I am not convinced they are real failures @cjcolvar

2021-05-06 15:14 UTC, cjcolvar commented
Superseded by #261

2021-05-06 15:14 UTC, closed without merging